### ISSUE TITLE
Segmentation fault 11

### ISSUE THREAD

**Issue by tonybuckingham** [groue/GRMustache.swift#1]
App runs fine in simulator and on device, but when archiving for deployment, compiler chokes with Segmentation fault, and the following output:

While emitting IR SIL function @_TTSGSaV16theabsolutesound11MustacheBox_GSaS0__Ss14CollectionType_GVSs17IndexingGeneratorGSaS0___GS2_GSaS0___Ss13GeneratorType_S0_S0_S_15MustacheBoxable_SiSiSs16ForwardIndexType_SiSiSs18_SignedIntegerType_SiSiSs33_BuiltinIntegerLiteralConvertible_Si_S0____TF16theabsolutesoundP33_923FE48AD3BF7E753B76F3E22D01634016renderCollectionUSs14CollectionType_USs13GeneratorType_S_15MustacheBoxable_Ss16ForwardIndexType_Ss18_SignedIntegerType_Ss33_BuiltinIntegerLiteralConvertible____FTQ_VS_13RenderingInfoGVSs33AutoreleasingUnsafeMutablePointerGSqCSo7NSError___GSqVS_9Rendering_ for 'renderCollection' at /u/theabsolutesound/theabsolutesound/Mustache/Rendering/MustacheBox.swift:979:9

Seemingly to do with:

private func renderCollection<C: CollectionType where C.Generator.Element: MustacheBoxable, C.Index: BidirectionalIndexType, C.Index.Distance == Int>(collection: C, var info: RenderingInfo, error: NSErrorPointer) -> Rendering? {

Just upgraded to Xcode 6.2, and hadn't ever archived in previous version, so can't say whether this is a bug introduced by 6.2 or not.

Any ideas what might be going on here?

**Comment by groue** [comment]
Hi Tony,

Yes, I have the issue as well with Xcode 6.2. It looks like the compiler options used when archiving choke on MustacheBox.swift at line 979.

I don't quite know yet what is happening.

**Comment by groue** [comment]
@tonybuckingham, will you update your master branch, and check again, please?

**Comment by tonybuckingham** [comment]
Yep, works now . . . thank you!

**Comment by groue** [comment]
You're welcome Tony. Happy Mustache!
