### ISSUE TITLE
GRMustache interferes with the AnyObject subscript (Cast from 'MustacheBox!' to unrelated type 'String' always fails)

### ISSUE THREAD

**Issue by crarau** [groue/GRMustache.swift#12]
Before using Mustache.swift the codebase was accessing the subscript of an AnyObject (that was a Dictionary underneath). I know it's not a best practice but this was working. 
After adding Mustache, it seems that the subscript access is override and a MustacheBox is returned.

I looked at the MustacheBox and I can't figure out why this is happening.

![image](https://cloud.githubusercontent.com/assets/1430145/10436602/6d223232-70f5-11e5-91bb-0af9b7091e87.png)

We easily fixed the issue by not treating the Dictionary like an AnyObject but like an Dictionary. But I'd like to understand why MustacheBox interfered with the AnyObject subscript.

Thanks for the library, it's so useful!

Note: I'm using the Swift2 branch

**Comment by groue** [comment]
Hello @crarau

Things are indeed weird:

```swift
let dict:[String: AnyObject] = ["key": "value"]
let anyObject = dict as AnyObject

let v2 = anyObject["key"]   // Alt-click on v2: MustacheBox!
print(v2.dynamicType)       // Prints ImplicitlyUnwrappedOptional<MustacheBox>
print(v2.value)             // Crash

let v3 = anyObject["key"]!  // Alt-click on v3: MustacheBox
print(v3.dynamicType)       // Prints _NSContiguousString
```

So we're facing a paticularly crazy Swift bug.

After refactoring the subscript functions declared by GRMustache, I could spot the origin of the problem:

```swift
final public class MustacheBox : NSObject {
    public subscript (key: String) -> MustacheBox
}
```

OK, so:

- I'll open a bug report to Apple.
- I'll refactor this subscript function into a regular function.
- I'll publish a new GRMustache.swift version.

Thanks again for opening thise issue, stay tuned!

**Comment by groue** [comment]
For what it's worth, Xcode 7.1 beta 3 (7B85) still has the issue.

**Comment by groue** [comment]
Next release is coming shortly.

**Comment by groue** [comment]
Please update to GRMustache v0.11.0. Oh, and please stick to tagged versions. Forget about branches, because they may contain unstable code.

**Comment by groue** [comment]
rdar://23122734 (http://openradar.appspot.com/radar?id=4952382538514432)
