### ISSUE TITLE
IOS7 and Xcode 7.0.1

### ISSUE THREAD

**Issue by aalonzi** [groue/GRMustache.swift#13]
Hello, can I still to use GRMustache.swift with target ios7 Xcode 7? I try to copy manually the sources, but have some error (eg. attach).

With GRMustache.swift 0.9.4 anche Xcode 6 I had no problems

Thank's
![schermata 2015-10-13 alle 23 24 59](https://cloud.githubusercontent.com/assets/1537212/10468861/cff73788-7201-11e5-9e93-8d7c70f8e24d.png)

**Comment by groue** [comment]
Oops, you're right. Let me check if it can be fixed.

**Comment by groue** [comment]
Thanks for the notice. The issue has been fixed. Next release is coming shortly.

**Comment by aalonzi** [comment]
Thank you Gwendal, your work is great!

**Comment by groue** [comment]
Thank you @aalonzi ! Happy Mustache :-)

**Comment by groue** [comment]
BTW, look in the DemoApp folder: there is an iOS7 app in there that may help if you need any hints.

**Comment by groue** [comment]
The fix is shipped in GRMustache v0.11.0.
