### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by njdehoog** [groue/GRMustache.swift#14]
Hey @groue, it's me again ;) Have you ever noticed any memory leaks in the framework? I have some memory leaks in my app, and when I use Instruments to track down the leak, it seems to point to GRMustache as the source:

![screen shot 2015-10-21 at 16 24 00](https://cloud.githubusercontent.com/assets/1107150/10639378/35825722-7810-11e5-9a42-4aec7554d471.png)

I spent a bunch of time trying to figure out what could be the root cause, and if maybe I was doing something wrong that would cause this issue, but I can't figure it out. Do you have any ideas maybe?

**Comment by groue** [comment]
Oops. Let me check.

**Comment by njdehoog** [comment]
Note that I can't reproduce the issue in the sample app.

**Comment by groue** [comment]
I may have to ask you some sample code. We're not there yet.

**Comment by njdehoog** [comment]
I was afraid you were gonna said that ;) I'll see if I can isolate the problem in a sample project. This might take a while...

**Comment by groue** [comment]
Don't do it now, let me try to reproduce first!

**Comment by njdehoog** [comment]
Too late. I've copied some stuff over from my project and I was able to reproduce the issue. Try profiling the OS X demo app and you should see the memory leaks after rendering.

Here's the debug project:
https://www.dropbox.com/s/inttwlrhqgde2z3/GRMustache.swift.zip?dl=0

**Comment by groue** [comment]
Thanks Niels :-) OK I'm looking at that very soon. Hold on!

**Comment by njdehoog** [comment]
Sounds good :+1: Let me know if I can help.

**Comment by groue** [comment]
Thanks for your sample code, I can reproduce the leak. It's pretty tricky, actually! Still investigating :-)

**Comment by groue** [comment]
@njdehoog I have good reasons to think that these leaks come from Swift itself. I expect them to vanish with Swift 3.
