### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by harlanhaskins** [groue/GRMustache.swift#16]
Now that Swift is open source, the need for a robust templating library has skyrocketed. I'd love to be able to use GRMustache on Linux, and since it doesn't depend on the Obj-C runtime, GRMustache is an awesome candidate!

Could we get a Swift package manager package?

**Comment by groue** [comment]
That would be a pleasure :-)

**Comment by Colton** [comment]
+1. I would love to see this have SPM support.

**Comment by groue** [comment]
@harlanhaskins, @Colton Done: [1.0.0rc1](https://github.com/groue/GRMustache.swift/tree/1.0.0rc1) is out.

Will you check https://github.com/groue/GRMustache.swift/tree/Swift2.2#swift-package-manager?

**Comment by groue** [comment]
It works! But I had to tag the release with the 1.0.0 tag.

**Comment by groue** [comment]
Swift issue about the mandatory `1.0.0` tag: https://bugs.swift.org/browse/SR-113

**Comment by groue** [comment]
OK now that's done. Check [groue/GRMustacheSPM](https://github.com/groue/GRMustacheSPM) for a sample Swift package that uses GRMustache.swift.

**Comment by Colton** [comment]
@groue Thank you!
