### ISSUE TITLE
Swift 2.2: Var bindings in closures and function calls are not supported.

### ISSUE THREAD

**Issue by harlanhaskins** [groue/GRMustache.swift#17]
https://gist.github.com/harlanhaskins/f227e53d3841d9bad957

Lots of build errors.

**Comment by groue** [comment]
A work in progress!

**Comment by harlanhaskins** [comment]
[!http://mrwgifs.com/wp-content/uploads/2013/03/Fred-Savage-Thumbs-Up-Reaction-Gif.gif]

**Comment by groue** [comment]
Fixed by [1.0.0rc1](https://github.com/groue/GRMustache.swift/tree/1.0.0rc1)

**Comment by harlanhaskins** [comment]
:+1: !!!
