### ISSUE TITLE
Retrieving NSAttributedString objects instead of NSString objects

### ISSUE THREAD

**Issue by kenjitayama** [groue/GRMustache.swift#19]
Same feature request as in issue https://github.com/groue/GRMustache/issues/60 , for the Objective-C version.
I'd like to write Value Filters that return NSAttributedString, and the rendering result in NSAttributedString.
Has the situation changed in the Swift version?

**Comment by groue** [comment]
Thanks for asking! And... no, not at all. I'll keep GRMustache focused on producing strings, and [NSHTMLTextDocumentType ](https://developer.apple.com/library/ios/documentation/UIKit/Reference/NSAttributedString_UIKit_Additions/#//apple_ref/doc/constant_group/Document_Types) is still your friend.
