### ISSUE TITLE
Carthage build

### ISSUE THREAD

**Issue by RayAnd** [groue/GRMustache.swift#20]
Hi,

Tried to install latest 1.0.0 version using Carthage and have following issue:

*** Building scheme "MustacheiOS" in Mustache.xcworkspace
** BUILD FAILED **

The following build commands failed:
	ProcessInfoPlistFile /Users/rayand/Library/Developer/Xcode/DerivedData/Mustache-docnnakqnaasqpccvubxiwwwydbs/Build/Products/Release-iphoneos/Mustache.framework/Info.plist Mustache/Info.plist
(1 failure)
error: could not read data from '/Users/rayand/Projects/Freelance/MobileAngels/isangel/iOSApplication/SnowAngel/SnowAngel/Carthage/Checkouts/GRMustache.swift/Xcode/Mustache/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file.
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	ProcessInfoPlistFile /Users/rayand/Library/Developer/Xcode/DerivedData/Mustache-docnnakqnaasqpccvubxiwwwydbs/Build/Products/Release-iphoneos/Mustache.framework/Info.plist Mustache/Info.plist
(1 failure)

I'm on latest Xcode and latest Carthage.

Thanks.

**Comment by RayAnd** [comment]
Version 0.11.0 build absolutely fine on same machine.

**Comment by groue** [comment]
Hello,

I have to update the documentation, but yes, stick with 0.11.0 for now.

1.0.0 adds nothing but the ability to target the Swift Package Manager. It should still work with Xcode projects and Carthage, but it has rough edges, obviously.

I apologize for the inconvenience.

**Comment by groue** [comment]
Cathage support is fixed in version 1.0.1.
