### ISSUE TITLE
typo in ZipFilter.swift?

### ISSUE THREAD

**Issue by denisbetsi** [groue/GRMustache.swift#27]
Line 40:
``zippedGenerators.append(AnyGenerator(array.generate()))  `` <-- errors out with AnyGenerator not accepting any arguments

should it perhaps be
``zippedGenerators.append(anyGenerator(array.generate()))``

**Comment by groue** [comment]
Hello @denisbetsi.

AnyGenerator or anyGenerator depends on the Swift version. Which one are you using, and on which platform (apple or linux) ?

**Comment by acgs** [comment]
I have the same issue - on Apple using XCode 7.2.1 and Swift 2.1.1. Currently updating to XCode 7.3 and Swift 2.2, so we'll see if that changes things.

**Comment by denisbetsi** [comment]
I have same setup as as acgs.

**Comment by acgs** [comment]
Just checked with new XCode - looks like anyGenerator is deprecated now in Swift 2.2, and it is preferred to use AnyGenerator. So, this issue can probably be closed, @groue.

**Comment by groue** [comment]
You are right, @acgs. The current state of GRMustache works fine with Xcode 7.3.
