### ISSUE TITLE
Swift 3.1 and warnings.

### ISSUE THREAD

**Issue by peterdeweese** [groue/GRMustache.swift#44]
Two warnings appear, both: "String interpolation produces a debug description for an optional value; did you mean to make this explicit?"

Would you like me to produce a PR to resolve it? If I do, what version of swift should it work back to?

**Comment by groue** [comment]
Hello @peterdeweese,

I think this has already been fixed by #43, and merged in the master branch. Do you confirm?

I haven't pushed a new version tag: that's what missing.

**Comment by peterdeweese** [comment]
Looks like it. Can you push that tag and update the spec when you get a chance?

**Comment by brentleyjones** [comment]
Is it possible to get a new release? Thanks.

**Comment by brentleyjones** [comment]
This is one of the last warnings in our project. Would be nice to have a new release. Thanks!

**Comment by fumito-ito** [comment]
#43 is tagged as 2.1.0.
