### ISSUE TITLE
Do not work with Swift 4 

### ISSUE THREAD

**Issue by shivayogic** [groue/GRMustache.swift#51]
Currently pod is not working with Swift 4. Is there any time frame I can expect Swift 4 version?

**Comment by Zyphrax** [comment]
@groue Any news on Swift 4 support? Thanks!

**Comment by gelliott181** [comment]
@groue Also interested in any updates on this.

If there's not time for you to tag Swift 3 support (per your response in #44) and then update and tag Swift 4 I can take a stab and PR it. This is the last blocker to my project being 100% Swift 4 compatible.

**Comment by richardkeen** [comment]
@groue Really interested to see Swift 4 support merged in. At the moment we are needing to pull in a fork (maximkhatskevich), which is obviously not ideal.

**Comment by rkbansal** [comment]
Will be very helpful to have Swift 4 support

**Comment by fumito-ito** [comment]
see #57 .
