### ISSUE TITLE
3.1.0 and 4.0.0 releases not available via Cocoapods

### ISSUE THREAD

**Issue by richardkeen** [groue/GRMustache.swift#59]
Firstly, thanks very much for the Swift 4 and Swift 5 compatible releases, it's great to no longer be depending on a fork of this project, particularly as we use it as a sub-dependency of our own framework.

The issue I'm seeing is that the 3.1.0 (Swift 4) and 4.0.0 (Swift 5) releases are not available as Cocoapods dependencies without pointing the Podfile at the relevant git tag explicitly. Whilst this is possible, although not desirable, for project Podfiles, it is not supported for sub-dependencies specified in Podspecs where only a version specification is supported.

The version in the `GRMustache.swift.podspec` file for both these releases is still set to `2.0.0` which would appear to be the root of the problem.

**Comment by kealist** [comment]
Also experiencing this
