### ISSUE TITLE
Deprecated 'class' keyword

### ISSUE THREAD

**Issue by BlixLT** [groue/GRMustache.swift#79]
We are trying to get rid of all warnings in our project and noticed one in Mustache:

`xxx/Tag.swift:56:22: Using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead`

Hopefully you will fix this in the future. Thanks.

**Comment by groue** [comment]
Hello @BlixLT,

I do not actively maintain this repository any longer. However, well-motivated and quality pull requests will be considered.
