### ISSUE TITLE
Post-rendering Lambda?

### ISSUE THREAD

**Issue by agiletortoise** [groue/GRMustache.swift#83]
Apologies if I'm missing it, but is there a way to have a lambda/filter/whatever that post-processes the rendering of its nested content. I want to have something like:

```
{{#section}}{{value}}{{/section}}
```

But where the `section` has access to and post-processes the renderer result of its nested content. Right now the Lambda get `{{value}}` as its string input. I want it to get the post-rendered version to process.

**Comment by agiletortoise** [comment]
I should probably clarify more, that I do not want what HTMLEscape does, intervening in individual tags, but want the `section` to have the final rendering of its child content to manipulate, not just modify each sub tag as it is renderered.

**Comment by groue** [comment]
Hello @agiletortoise,

Please check the [Advanced Boxes](https://github.com/groue/GRMustache.swift/blob/master/README.md#advanced-boxes) documentation chapter, and probably one of the `render`, `willRender` or `didRender` initializers.

You will have to read the documentation.
