### ISSUE TITLE
Problems with PFObject

### ISSUE THREAD

**Issue by jimijon** [groue/GRMustache.swift#93]
I had issued a previous issue request but failed to truly debug the issue. The issue is that it doesn't work with PFObject. It doesn't seem to fail, just removes everything. The old pod version of this worked and continues to work but we need to move to SPM.

**Comment by fumito-ito** [comment]
What's PFObject ?

**Comment by jimijon** [comment]
It is a Parse Platform object:

[https://parseplatform.org/Parse-SDK-iOS-OSX/api/Classes/PFObject.html](https://parseplatform.org/Parse-SDK-iOS-OSX/api/Classes/PFObject.html)

**Comment by fumito-ito** [comment]
@jimijon 

GRMustache.swift I have never used Parse Platform and do not understand how PFObject is structured. If you would like, please read the public GRMustache.swift source code and send me a PR that solves the problem. We are always open to PRs.
