### ISSUE TITLE
GRMustache not compatible with Swift 6 concurrency checking

### ISSUE THREAD

**Issue by clausjoergensen** [groue/GRMustache.swift#98]
![image](https://github.com/user-attachments/assets/6ae9995e-26fa-4d4a-a05a-b2a0aae88ecd)

And unfortunately importing Mustache with `@preconcurrency` doesn't prevent this error.

**Comment by fumito-ito** [comment]
@clausjoergensen 
Thank you for your report. Could you please provide a development environment and/or the minimal code that reproduces the problem you reported, if any?

**Comment by clausjoergensen** [comment]
I mean, sure, but as mentioned, it's a Swift 6 concurrency error, any project where you turn on Strict Concurrency Checking (`SWIFT_STRICT_CONCURRENCY = complete`) will show this warning. And if the project has Swift Compiler - Threat Warnings as Errors enabled (`SWIFT_TREAT_WARNINGS_AS_ERRORS = YES`) it'll be a compilation error (as any Swift Package will inherit the compilation flags of the project is embedded in)

Full sample (requires Xcode 16): [MustacheSwift6.zip](https://github.com/user-attachments/files/16589376/MustacheSwift6.zip)

**Comment by clausjoergensen** [comment]
That said, it does appear Apple have fixed the `@preconcurrency` import in latest Xcode beta. But it would probably be a great idea to look into a way to fix this regardless :)
